version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: academic-portal
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: academic-portal-express
    restart: always
    ports:
      - 9090:9090
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=academic-portal
volumes:
  data: {}

networks:
  default:
    name: mongodb_network